#!/usr/bin/env bash
#a script that gives you information about the school file.
if [ -e school ] 
then 
    if [ ! -s school ]
then
    echo "school file is empty"
else
    echo "school file is not empty"
fi

    echo "school file exists"

    if [ -f school ]
then
    echo "school is a regular file"
else
    echo ""
fi
else
    echo "school file does not exist"
fi
