#!/usr/bin/env bash
#a script that shows PID and process name of processes containing "bash"

for pid in /proc/[0-9]*/comm
do
    name=$(cat "$pid" 2>/dev/null)
    if echo "$name" | grep -q bash; then
        echo "$(basename "$(dirname "$pid")") $name"
    fi
done
