#!/usr/bin/env bash
#kills any process running 7-highlander

for pid_dir in /proc/[0-9]*; do
    cmdline_file="$pid_dir/cmdline"

    # skip if we can't read cmdline
    [ -r "$cmdline_file" ] || continue

    # read cmdline (it's NUL-separated, turn NULs into spaces)
    cmd=$(tr '\0' ' ' < "$cmdline_file")

    case "$cmd" in
        *7-highlander*)
            kill -9 "$(basename "$pid_dir")"
            ;;
    esac
done
